spring.application.name=authsphere-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/authsphere
spring.datasource.username=postgres
spring.datasource.password=Satya@2006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

server.port=8081

# Spring Security Debug Logging
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=VGhpc0lzQVVsdHJhU2VjcmV0S2V5Rm9yQXV0aFNwaGVyZUFwcGxpY2F0aW9uMTIzNDU2Nzg5MDEyMzQ1Ng==
jwt.expiration=86400000

# Email verification token expiry - 1 hour
auth.verification-token-expiration=3600000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=authsphere.project@gmail.com
spring.mail.password=khgpdvohsthbarpz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000